import type { BuilderElement } from "./builder-store";
import { v4 as uuid } from "uuid";

function el(type: string, props: Record<string, unknown>): BuilderElement {
  return { id: uuid(), type: type as any, props };
}

export const STARTER_TEMPLATES: { name: string; elements: BuilderElement[] }[] = [
  {
    name: "Event Page",
    elements: [
      el("section", { bgColor: "#1a0a12", bgGradient: "linear-gradient(to bottom, #3A0F2A, #1A0814)", padding: "64", maxWidth: "900", borderTop: false }),
      el("heading", { text: "Event Name Here", level: "h1", align: "center", color: "#ffffff" }),
      el("text", { text: "Date · Location · Time", align: "center", color: "#FFB3D0", fontSize: "14" }),
      el("spacer", { height: "24" }),
      el("image", { src: "", alt: "Event banner", width: "100%", borderRadius: "16" }),
      el("spacer", { height: "32" }),
      el("text", { text: "Describe your event here. What makes it special? What can attendees expect? Add all the details that will get your amigas excited!", align: "left", color: "#e0e0e0", fontSize: "16" }),
      el("spacer", { height: "24" }),
      el("heading", { text: "What's Included", level: "h3", align: "left", color: "#FFB3D0" }),
      el("text", { text: "• Item one\n• Item two\n• Item three\n• Item four", align: "left", color: "#999999", fontSize: "14" }),
      el("spacer", { height: "32" }),
      el("divider", { color: "#FF0099", opacity: "0.2", width: "60%" }),
      el("spacer", { height: "32" }),
      el("heading", { text: "Ready to Join?", level: "h2", align: "center", color: "#ffffff" }),
      el("text", { text: "Spots are limited — reserve yours now!", align: "center", color: "#999999", fontSize: "16" }),
      el("spacer", { height: "16" }),
      el("button", { text: "Register Now ♡", href: "/register", variant: "primary", align: "center" }),
    ],
  },
  {
    name: "Trip Detail",
    elements: [
      el("section", { bgColor: "#1A0814", bgGradient: "linear-gradient(135deg, #3A0F2A, #1A0814)", padding: "64", maxWidth: "900", borderTop: false }),
      el("heading", { text: "Destination Name", level: "h1", align: "center", color: "#ffffff" }),
      el("text", { text: "🌎 Country · Dates · Duration", align: "center", color: "#FFB3D0", fontSize: "14" }),
      el("spacer", { height: "24" }),
      el("image", { src: "", alt: "Destination photo", width: "100%", borderRadius: "16" }),
      el("spacer", { height: "32" }),
      el("heading", { text: "About This Trip", level: "h2", align: "left", color: "#ffffff" }),
      el("text", { text: "Write a compelling description of the trip. What will amigas experience? What makes this destination special?", align: "left", color: "#e0e0e0", fontSize: "16" }),
      el("spacer", { height: "24" }),
      el("card", { title: "Trip Highlights", description: "• Highlight one\n• Highlight two\n• Highlight three\n• Highlight four\n• Highlight five", bgColor: "#3A0F2A", borderColor: "#FF0099" }),
      el("spacer", { height: "16" }),
      el("card", { title: "What's Included", description: "• Accommodation\n• Most meals\n• All excursions\n• Airport transfers\n• Trip leader", bgColor: "#3A0F2A", borderColor: "#DAA520" }),
      el("spacer", { height: "32" }),
      el("heading", { text: "$X,XXX per person", level: "h2", align: "center", color: "#FF0099" }),
      el("text", { text: "Payment plans available — from $XXX deposit", align: "center", color: "#999999", fontSize: "14" }),
      el("spacer", { height: "16" }),
      el("button", { text: "Book This Trip ♡", href: "/trips", variant: "primary", align: "center" }),
    ],
  },
  {
    name: "Blog Post",
    elements: [
      el("section", { bgColor: "#1A0814", bgGradient: "", padding: "48", maxWidth: "800", borderTop: false }),
      el("text", { text: "TRAVEL · APRIL 2026", align: "center", color: "#FF0099", fontSize: "12" }),
      el("heading", { text: "Your Blog Post Title Here", level: "h1", align: "center", color: "#ffffff" }),
      el("text", { text: "By Author Name", align: "center", color: "#666666", fontSize: "14" }),
      el("spacer", { height: "32" }),
      el("image", { src: "", alt: "Blog hero image", width: "100%", borderRadius: "16" }),
      el("spacer", { height: "32" }),
      el("text", { text: "Start writing your blog post here. Share travel tips, trip recaps, community stories, or anything that inspires your amigas.\n\nUse multiple text blocks to break up long content. Add images between sections for visual interest.", align: "left", color: "#e0e0e0", fontSize: "16" }),
      el("spacer", { height: "24" }),
      el("heading", { text: "Section Heading", level: "h2", align: "left", color: "#ffffff" }),
      el("text", { text: "Continue your story here. Each section can cover a different topic or highlight from your experience.", align: "left", color: "#e0e0e0", fontSize: "16" }),
      el("spacer", { height: "24" }),
      el("image", { src: "", alt: "In-article photo", width: "100%", borderRadius: "12" }),
      el("spacer", { height: "24" }),
      el("text", { text: "Wrap up your post with a conclusion or call to action.", align: "left", color: "#e0e0e0", fontSize: "16" }),
      el("spacer", { height: "32" }),
      el("divider", { color: "#FF0099", opacity: "0.2", width: "40%" }),
      el("spacer", { height: "16" }),
      el("button", { text: "Join the Community ♡", href: "/register", variant: "primary", align: "center" }),
    ],
  },
  {
    name: "Photo Gallery",
    elements: [
      el("section", { bgColor: "#1A0814", bgGradient: "linear-gradient(to bottom, #3A0F2A, #1A0814)", padding: "48", maxWidth: "1000", borderTop: false }),
      el("heading", { text: "Photo Gallery Title", level: "h1", align: "center", color: "#ffffff" }),
      el("text", { text: "A collection of memories from our adventures together.", align: "center", color: "#999999", fontSize: "16" }),
      el("spacer", { height: "32" }),
      el("image", { src: "", alt: "Gallery photo 1", width: "100%", borderRadius: "12" }),
      el("spacer", { height: "12" }),
      el("image", { src: "", alt: "Gallery photo 2", width: "100%", borderRadius: "12" }),
      el("spacer", { height: "12" }),
      el("image", { src: "", alt: "Gallery photo 3", width: "100%", borderRadius: "12" }),
      el("spacer", { height: "12" }),
      el("image", { src: "", alt: "Gallery photo 4", width: "100%", borderRadius: "12" }),
      el("spacer", { height: "32" }),
      el("button", { text: "See More Photos", href: "/gallery", variant: "outline", align: "center" }),
    ],
  },
  {
    name: "Blank Dark Page",
    elements: [
      el("section", { bgColor: "#1A0814", bgGradient: "", padding: "64", maxWidth: "900", borderTop: false }),
      el("heading", { text: "Page Title", level: "h1", align: "center", color: "#ffffff" }),
      el("spacer", { height: "24" }),
      el("text", { text: "Start building your page content here.", align: "center", color: "#999999", fontSize: "16" }),
    ],
  },
];
