"use client";

/**
 * Supabase implementation of useTripReservations, useMyTripReservations
 * and useAllReservations. Delegated to from use-trip-reservations.ts /
 * use-all-reservations.ts when useSupabaseBackend is on. Reservations
 * live in the flat `trip_reservations` table (id default-generated by
 * Postgres), mirroring the flat Firestore collection so the admin
 * roster reads everything with one subscription.
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import { getSupabase } from "./supabase";
import { subscribeQuery, tsToIso, nowIso } from "./supabase-helpers";
import { useAuth } from "./store";
import { pushNotification } from "./notify";
import { getTripById } from "./trips-data";
import type {
  ReservationStatus,
  TripReservation,
  UseTripReservationsResult,
} from "./use-trip-reservations";

interface ReservationRow {
  id: string;
  trip_id: string;
  user_id: string;
  user_name: string | null;
  user_avatar: string | null;
  status: string | null;
  note: string | null;
  created_at: string | null;
}

function rowToReservation(r: ReservationRow): TripReservation {
  return {
    id: r.id,
    tripId: r.trip_id ?? "",
    userId: r.user_id ?? "",
    userName: r.user_name ?? "Amiga",
    userAvatar: r.user_avatar ?? undefined,
    status:
      r.status === "waitlist"
        ? "waitlist"
        : r.status === "cancelled"
          ? "cancelled"
          : "reserved",
    note: r.note ?? undefined,
    createdAt: tsToIso(r.created_at),
  };
}

/* ------------------------------------------------------------------ */
/* Per-trip hook (reserve button + trip detail)                        */
/* ------------------------------------------------------------------ */

export function useTripReservationsSupabase(
  tripId: string | null | undefined,
  totalSpots: number,
): UseTripReservationsResult {
  const user = useAuth((s) => s.user);
  const [reservations, setReservations] = useState<TripReservation[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!tripId) {
      setReservations([]);
      setLoading(false);
      return;
    }
    setLoading(true);
    const unsub = subscribeQuery<ReservationRow>(
      "trip_reservations",
      (sb) => sb.from("trip_reservations").select("*").eq("trip_id", tripId),
      (rows) => {
        setReservations(
          rows
            .map(rowToReservation)
            .sort((a, b) =>
              (a.createdAt || "￿").localeCompare(b.createdAt || "￿"),
            ),
        );
        setLoading(false);
      },
      (msg) => {
        console.warn("[trip-reservations:sb] query failed", msg);
        setLoading(false);
      },
      { column: "trip_id", value: tripId },
    );
    return unsub;
  }, [tripId]);

  const reserved = useMemo(
    () => reservations.filter((r) => r.status === "reserved"),
    [reservations],
  );
  const waitlist = useMemo(
    () => reservations.filter((r) => r.status === "waitlist"),
    [reservations],
  );

  const spotsLeft = Math.max(0, totalSpots - reserved.length);
  const isFull = spotsLeft <= 0;

  // Rows carry the canonical users.id (store id) — RLS maps the JWT to
  // it, so the store id is the right key to match my own row by.
  const myReservation = useMemo(() => {
    if (!user) return null;
    return (
      reservations.find(
        (r) => r.userId === user.id && r.status !== "cancelled",
      ) ?? null
    );
  }, [reservations, user]);

  const reserve = useCallback(
    async (note?: string): Promise<ReservationStatus | null> => {
      if (!tripId || !user) return null;
      const sb = getSupabase();
      if (!sb) return null;

      // Already holding an active reservation? Return it untouched so
      // the toggle is idempotent.
      if (myReservation) return myReservation.status;

      // Re-activate a previously cancelled reservation rather than
      // stacking a duplicate row.
      const prior = reservations.find(
        (r) => r.userId === user.id && r.status === "cancelled",
      );
      const status: ReservationStatus = isFull ? "waitlist" : "reserved";

      try {
        if (prior) {
          const { error } = await sb
            .from("trip_reservations")
            .update({
              status,
              note: note?.trim() || null,
              created_at: nowIso(),
            })
            .eq("id", prior.id);
          if (error) throw new Error(error.message);
        } else {
          const { error } = await sb.from("trip_reservations").insert({
            trip_id: tripId,
            user_id: user.id,
            user_name: user.name,
            user_avatar: user.avatar ?? null,
            status,
            note: note?.trim() || null,
            created_at: nowIso(),
          });
          if (error) throw new Error(error.message);
        }

        // Confirm to the member.
        const trip = getTripById(tripId);
        const tripName = trip?.title ?? "your trip";
        void pushNotification(user.id, {
          kind: "reservation",
          title:
            status === "reserved"
              ? `You're booked for ${tripName} 🎉`
              : `You're on the waitlist for ${tripName}`,
          body:
            status === "reserved"
              ? "Your spot is saved. We'll be in touch with next steps."
              : "We'll let you know the moment a seat opens up.",
          href: "/community/my-events",
        });
        return status;
      } catch (err) {
        console.error("[trip-reservations:sb] reserve failed", err);
        return null;
      }
    },
    [tripId, user, myReservation, reservations, isFull],
  );

  const cancel = useCallback(async (): Promise<boolean> => {
    if (!user || !myReservation) return false;
    const sb = getSupabase();
    if (!sb) return false;
    const { error } = await sb
      .from("trip_reservations")
      .update({ status: "cancelled" })
      .eq("id", myReservation.id);
    if (error) {
      console.error("[trip-reservations:sb] cancel failed", error.message);
      return false;
    }
    return true;
  }, [user, myReservation]);

  return {
    reservations,
    reserved,
    waitlist,
    reservedCount: reserved.length,
    waitlistCount: waitlist.length,
    spotsLeft,
    isFull,
    myReservation,
    loading,
    isFirebase: true,
    reserve,
    cancel,
  };
}

/* ------------------------------------------------------------------ */
/* Per-member hook (My Upcoming)                                       */
/* ------------------------------------------------------------------ */

export function useMyTripReservationsSupabase(): {
  reservations: TripReservation[];
  loading: boolean;
} {
  const uid = useAuth((s) => s.user?.id);
  const [reservations, setReservations] = useState<TripReservation[]>([]);
  const [loading, setLoading] = useState<boolean>(Boolean(uid));

  useEffect(() => {
    if (!uid) {
      setReservations([]);
      setLoading(false);
      return;
    }
    setLoading(true);
    const unsub = subscribeQuery<ReservationRow>(
      "trip_reservations",
      (sb) => sb.from("trip_reservations").select("*").eq("user_id", uid),
      (rows) => {
        setReservations(
          rows
            .map(rowToReservation)
            .filter((r) => r.status !== "cancelled")
            .sort((a, b) => (a.createdAt || "").localeCompare(b.createdAt || "")),
        );
        setLoading(false);
      },
      (msg) => {
        console.warn("[trip-reservations:sb] my-query failed", msg);
        setLoading(false);
      },
      { column: "user_id", value: uid },
    );
    return unsub;
  }, [uid]);

  return { reservations, loading };
}

/* ------------------------------------------------------------------ */
/* Admin roster (Leads page + agreements recipient picker)             */
/* ------------------------------------------------------------------ */

export function useAllReservationsSupabase(): {
  reservations: TripReservation[];
  loading: boolean;
  error: boolean;
} {
  const [reservations, setReservations] = useState<TripReservation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    const unsub = subscribeQuery<ReservationRow>(
      "trip_reservations",
      (sb) => sb.from("trip_reservations").select("*").limit(1000),
      (rows) => {
        setReservations(
          rows
            .map(rowToReservation)
            .sort((a, b) =>
              (b.createdAt || "").localeCompare(a.createdAt || ""),
            ),
        );
        setError(false);
        setLoading(false);
      },
      (msg) => {
        console.warn("[reservations:sb] query failed", msg);
        setError(true);
        setLoading(false);
      },
    );
    return unsub;
  }, []);

  return { reservations, loading, error };
}
